### ISSUE TITLE
Doesn't work on Android 15 (pixel 8 pro beta)

### ISSUE THREAD

**Issue by Fefedu973** [KieronQuinn/ClassicPowerMenu#157] opened 2024-10-13 11:23 UTC
The power menu is closing as soon as it's opening.

**Comment by KieronQuinn** [comment] 2024-10-15 22:14
Duplicate of #143, fixed by a PR.

**Closed by KieronQuinn** 2024-10-15 22:14 UTC

**Comment by Fefedu973** [comment] 2024-10-17 19:37
Yes it worked thanks ☺️
