### ISSUE TITLE
A crash occurs when the app starts

### ISSUE THREAD

**Issue by YamazakuraH** [KieronQuinn/ClassicPowerMenu#6] opened 2021-10-04 02:23 UTC
New installation, after opening the app to authorize root, it will crash back.

log:
https://paste.ubuntu.com/p/qN89g3Md7V/

**Comment by rohitjakhar** [comment] 2021-10-04 03:17
Should i fixed it and create pull request ?

**Comment by KieronQuinn** [comment] 2021-10-04 09:25
Duplicate of #3

**Closed by KieronQuinn** 2021-10-04 09:25 UTC
