### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pbanj** [KieronQuinn/ClassicPowerMenu#23] opened 2021-11-25 02:43 UTC
It's only happened once but figured I'd report it

`FATAL EXCEPTION: main
Process: com.kieronquinn.app.classicpowermenu, PID: 9023
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2110636 bytes
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.os.TransactionTooLargeException: data parcel size 2110636 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:550)
	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4408)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
	... 7 more`

**Comment by KieronQuinn** [comment] 2022-03-19 00:34
I wasn't able to reproduce this and it looks like it's just a random error anyway, so I'll close this unless it keeps happening to someone.

**Closed by KieronQuinn** 2022-03-19 00:34 UTC
